## On branches other than main, lint the terraform code under infrastructure. When main is pushed, 
# apply the terraform code under infrastructure.
name: CI
on:
  push:
    branches:
      - main
      - 'feature/*'
      - 'bugfix/*'
      - 'hotfix/*'
  pull_request:
    branches:
      - main
      - 'feature/*'
      - 'bugfix/*'
      - 'hotfix/*'
      
env:
  TF_VERSION: 1.7.1
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  lint:
    name: Lint Terraform Code
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    environment: Azure   # This line links the job to your 'Azure' environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Lint Terraform code
        run: |
          cd infrastructure
          terraform init
          terraform fmt -check -recursive
          terraform validate

  apply:
    name: Apply Terraform Code
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: Azure   # This line links the job to your 'Azure' environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Apply Terraform code
        run: |
          cd infrastructure
          terraform init
          terraform apply -auto-approve
